openapi: 3.0.0
info:
  title: API Reclutamiento
  version: 1.0.0
  description: API REST para la gestión de reclutamiento.

servers:
  - url: http://localhost:8000/api
    description: Servidor local

tags:
  - name: Candidatos
    description: Operaciones sobre candidatos.
  - name: Candidatos_Cargos
    description: Relaciones entre candidatos y cargos.
  - name: Cargos
    description: Operaciones sobre cargos.
  - name: Comentarios
    description: Operaciones sobre comentarios.
  - name: Comunas
    description: Operaciones sobre comunas.
  - name: Documentos
    description: Operaciones sobre documentos.
  - name: Documentos_Candidatos
    description: Relaciones entre documentos y candidatos.
  - name: Estado_Candidatos
    description: Estados posibles de los candidatos.
  - name: Estados_Civiles
    description: Estados civiles disponibles.
  - name: Nacionalidades
    description: Operaciones sobre nacionalidades.
  - name: Regiones
    description: Operaciones sobre regiones.
  - name: Titulos_Profesionales
    description: Operaciones sobre títulos profesionales.

paths:
  /candidatos:
    get:
      tags:
        - Candidatos
      summary: Listar todos los candidatos
      responses:
        "200":
          description: Lista de candidatos
    post:
      tags:
        - Candidatos
      summary: Crear un candidato
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                rut:
                  type: string
                nombre_completo:
                  type: string
                titulo_profesional_id:
                  type: integer
                telefono:
                  type: string
                correo:
                  type: string
                estado_candidato_id:
                  type: integer
                nacionalidad_id:
                  type: integer
                estado_civil_id:
                  type: integer
                direccion:
                  type: string
                comuna_id:
                  type: integer
              required:
                - rut
                - nombre_completo
                - titulo_profesional_id
                - telefono
                - correo
                - nacionalidad_id
                - estado_civil_id
                - comuna_id
      responses:
        "201":
          description: Candidato creado

  /candidatos/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - Candidatos
      summary: Obtener un candidato por ID
      responses:
        "200":
          description: Candidato encontrado
    put:
      tags:
        - Candidatos
      summary: Actualizar un candidato
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                rut:
                  type: string
                nombre_completo:
                  type: string
                titulo_profesional_id:
                  type: integer
                telefono:
                  type: string
                correo:
                  type: string
                estado_candidato_id:
                  type: integer
                nacionalidad_id:
                  type: integer
                estado_civil_id:
                  type: integer
                direccion:
                  type: string
                comuna_id:
                  type: integer
      responses:
        "200":
          description: Candidato actualizado
    delete:
      tags:
        - Candidatos
      summary: Eliminar un candidato
      responses:
        "200":
          description: Candidato eliminado

  /candidatos_cargos:
    get:
      tags:
        - Candidatos_Cargos
      summary: Listar relaciones candidato–cargo
      responses:
        "200":
          description: Lista de relaciones
    post:
      tags:
        - Candidatos_Cargos
      summary: Crear relación candidato–cargo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                candidato_id:
                  type: integer
                cargo_id:
                  type: integer
              required:
                - candidato_id
                - cargo_id
      responses:
        "201":
          description: Relación creada

  /candidatos_cargos/{candidato_id}/{cargo_id}:
    parameters:
      - name: candidato_id
        in: path
        required: true
        schema:
          type: integer
      - name: cargo_id
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - Candidatos_Cargos
      summary: Obtener relación específica
      responses:
        "200":
          description: Relación encontrada
    delete:
      tags:
        - Candidatos_Cargos
      summary: Eliminar relación
      responses:
        "200":
          description: Relación eliminada

  /cargos:
    get:
      tags:
        - Cargos
      summary: Listar cargos
      responses:
        "200":
          description: Lista de cargos
    post:
      tags:
        - Cargos
      summary: Crear cargo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
              required:
                - nombre
      responses:
        "201":
          description: Cargo creado

  /cargos/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - Cargos
      summary: Obtener cargo por ID
      responses:
        "200":
          description: Cargo encontrado
    put:
      tags:
        - Cargos
      summary: Actualizar cargo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
      responses:
        "200":
          description: Cargo actualizado
    delete:
      tags:
        - Cargos
      summary: Eliminar cargo
      responses:
        "200":
          description: Cargo eliminado

  /comentarios:
    get:
      tags:
        - Comentarios
      summary: Listar comentarios
      responses:
        "200":
          description: Lista de comentarios
    post:
      tags:
        - Comentarios
      summary: Crear comentario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                candidato_id:
                  type: integer
                descripcion:
                  type: string
              required:
                - candidato_id
                - descripcion
      responses:
        "201":
          description: Comentario creado

  /comentarios/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - Comentarios
      summary: Obtener comentario por ID
      responses:
        "200":
          description: Comentario encontrado
    put:
      tags:
        - Comentarios
      summary: Actualizar comentario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                descripcion:
                  type: string
      responses:
        "200":
          description: Comentario actualizado
    delete:
      tags:
        - Comentarios
      summary: Eliminar comentario
      responses:
        "200":
          description: Comentario eliminado

  /comunas:
    get:
      tags:
        - Comunas
      summary: Listar todas las comunas
      responses:
        "200":
          description: Lista de comunas
    post:
      tags:
        - Comunas
      summary: Crear una comuna
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                region_id:
                  type: integer
              required:
                - nombre
                - region_id
      responses:
        "201":
          description: Comuna creada

  /comunas/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - Comunas
      summary: Obtener comuna por ID
      responses:
        "200":
          description: Comuna encontrada
    put:
      tags:
        - Comunas
      summary: Actualizar comuna
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                region_id:
                  type: integer
      responses:
        "200":
          description: Comuna actualizada
    delete:
      tags:
        - Comunas
      summary: Eliminar comuna
      responses:
        "200":
          description: Comuna eliminada

  /documentos:
    get:
      tags:
        - Documentos
      summary: Listar documentos
      responses:
        "200":
          description: Lista de documentos
    post:
      tags:
        - Documentos
      summary: Crear documento
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
              required:
                - nombre
      responses:
        "201":
          description: Documento creado

  /documentos/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - Documentos
      summary: Obtener documento por ID
      responses:
        "200":
          description: Documento encontrado
    put:
      tags:
        - Documentos
      summary: Actualizar documento
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
      responses:
        "200":
          description: Documento actualizado
    delete:
      tags:
        - Documentos
      summary: Eliminar documento
      responses:
        "200":
          description: Documento eliminado

  /documentos_candidatos:
    get:
      tags:
        - Documentos_Candidatos
      summary: Listar relaciones documento–candidato
      responses:
        "200":
          description: Lista de relaciones
    post:
      tags:
        - Documentos_Candidatos
      summary: Asociar documento a candidato
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                documento_id:
                  type: integer
                candidato_id:
                  type: integer
                ruta:
                  type: string
              required:
                - documento_id
                - candidato_id
                - ruta
      responses:
        "201":
          description: Relación creada

  /documentos_candidatos/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - Documentos_Candidatos
      summary: Obtener relación por ID
      responses:
        "200":
          description: Relación encontrada
    put:
      tags:
        - Documentos_Candidatos
      summary: Actualizar relación documento–candidato
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ruta:
                  type: string
      responses:
        "200":
          description: Relación actualizada
    delete:
      tags:
        - Documentos_Candidatos
      summary: Eliminar relación
      responses:
        "200":
          description: Relación eliminada

  /estado_candidatos:
    get:
      tags:
        - Estado_Candidatos
      summary: Listar estados de candidatos
      responses:
        "200":
          description: Lista de estados
    post:
      tags:
        - Estado_Candidatos
      summary: Crear estado de candidato
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
              required:
                - nombre
      responses:
        "201":
          description: Estado creado

  /estado_candidatos/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - Estado_Candidatos
      summary: Obtener estado de candidato
      responses:
        "200":
          description: Estado encontrado
    put:
      tags:
        - Estado_Candidatos
      summary: Actualizar estado de candidato
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
      responses:
        "200":
          description: Estado actualizado
    delete:
      tags:
        - Estado_Candidatos
      summary: Eliminar estado de candidato
      responses:
        "200":
          description: Estado eliminado

  /estados_civiles:
    get:
      tags:
        - Estados_Civiles
      summary: Listar estados civiles
      responses:
        "200":
          description: Lista de estados civiles
    post:
      tags:
        - Estados_Civiles
      summary: Crear estado civil
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
              required:
                - nombre
      responses:
        "201":
          description: Estado civil creado

  /estados_civiles/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - Estados_Civiles
      summary: Obtener estado civil por ID
      responses:
        "200":
          description: Estado civil encontrado
    put:
      tags:
        - Estados_Civiles
      summary: Actualizar estado civil
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
      responses:
        "200":
          description: Estado civil actualizado
    delete:
      tags:
        - Estados_Civiles
      summary: Eliminar estado civil
      responses:
        "200":
          description: Estado civil eliminado

  /nacionalidades:
    get:
      tags:
        - Nacionalidades
      summary: Listar nacionalidades
      responses:
        "200":
          description: Lista de nacionalidades
    post:
      tags:
        - Nacionalidades
      summary: Crear nacionalidad
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
              required:
                - nombre
      responses:
        "201":
          description: Nacionalidad creada

  /nacionalidades/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - Nacionalidades
      summary: Obtener nacionalidad por ID
      responses:
        "200":
          description: Nacionalidad encontrada
    put:
      tags:
        - Nacionalidades
      summary: Actualizar nacionalidad
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
      responses:
        "200":
          description: Nacionalidad actualizada
    delete:
      tags:
        - Nacionalidades
      summary: Eliminar nacionalidad
      responses:
        "200":
          description: Nacionalidad eliminada

  /regiones:
    get:
      tags:
        - Regiones
      summary: Listar regiones
      responses:
        "200":
          description: Lista de regiones
    post:
      tags:
        - Regiones
      summary: Crear región
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
              required:
                - nombre
      responses:
        "201":
          description: Región creada

  /regiones/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - Regiones
      summary: Obtener región por ID
      responses:
        "200":
          description: Región encontrada
    put:
      tags:
        - Regiones
      summary: Actualizar región
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
      responses:
        "200":
          description: Región actualizada
    delete:
      tags:
        - Regiones
      summary: Eliminar región
      responses:
        "200":
          description: Región eliminada

  /titulos_profesionales:
    get:
      tags:
        - Titulos_Profesionales
      summary: Listar títulos profesionales
      responses:
        "200":
          description: Lista de títulos profesionales
    post:
      tags:
        - Titulos_Profesionales
      summary: Crear título profesional
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
              required:
                - nombre
      responses:
        "201":
          description: Título profesional creado

  /titulos_profesionales/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - Titulos_Profesionales
      summary: Obtener título profesional por ID
      responses:
        "200":
          description: Título profesional encontrado
    put:
      tags:
        - Titulos_Profesionales
      summary: Actualizar título profesional
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
      responses:
        "200":
          description: Título profesional actualizado
    delete:
      tags:
        - Titulos_Profesionales
      summary: Eliminar título profesional
      responses:
        "200":
          description: Título profesional eliminado
